# Azure Devops Pipeline

trigger:
- Initial_H

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: 'out'
  jarName: 'cha2ds2-vasc.jar'
  mainClass: 'chadsVascCalculatorGUI'

stages:
- stage: Clone
  displayName: 'Clone Repository'
  jobs:
  - job: Checkout
    steps:
    - checkout: self

- stage: Compile
  displayName: 'Compile Java Files'
  jobs:
  - job: CompileJob
    steps:
    - script: |
        mkdir -p out
        find src -name "*.java" > sources.txt
        javac -d out @sources.txt
        echo " Confirming compiled classes are created:"
        ls -R out
        echo "Published files:"
        find out -type f 
      displayName: 'Compile .java files'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'out'
        ArtifactName: 'compiled-classes'
        publishLocation: 'Container'

- stage: Package
  displayName: 'Package JAR'
  jobs:
  - job: PackageJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'compiled-classes'
        downloadPath: 'downloaded'
    - script: |
        echo "Main-Class: chadsVascCalculatorGUI" > MANIFEST.MF
        echo “show what is inside downloaded:”
        ls -R downloaded
        jar cvfm cha2ds2-vasc.jar MANIFEST.MF -C downloaded/compiled-classes .
      displayName: 'Create JAR File'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true 

    - script: |
        echo "Checking JAR is created before publishing..."
        ls -l cha2ds2-vasc.jar
        mkdir upload
        cp cha2ds2-vasc.jar upload/
        pip install azure-devops
        az extension add --name azure-devops
        az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
        echo "##vso[task.setvariable variable=AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR]$(System.AccessToken)"
        az artifacts universal publish \
          --organization "$(System.TeamFoundationCollectionUri)" \
          --project "$(System.TeamProject)" \
          --scope project \
          --feed "chads-vasc-jar" \
          --name "cha2ds2-vasc" \
          --version "1.0.0-$(Build.BuildId)" \
          --description "CHA2DS2-VASc Java JAR" \
          --path "upload"
      env:
        AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR: $(System.AccessToken)
      displayName: 'Publish JAR to Azure Artifacts Feed'