# Azure Devops Pipeline

trigger:
- Initial_H

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: 'out'
  jarName: 'cha2ds2-vasc.jar'
  mainClass: 'chadsVascCalculatorGUI'

stages:
- stage: Clone
  displayName: 'Clone Repository'
  jobs:
  - job: Checkout
    steps:
    - checkout: self

- stage: Compile
  displayName: 'Compile Java Files'
  jobs:
  - job: CompileJob
    steps:
    - script: |
        mkdir -p out
        find src -name "*.java" > sources.txt
        javac -d out @sources.txt
        echo " Confirming compiled classes are created:"
        ls -R out
        echo "Published files:"
        find out -type f 
      displayName: 'Compile .java files'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'out'
        ArtifactName: 'compiled-classes'
        publishLocation: 'Container'

- stage: Package
  displayName: 'Package JAR'
  jobs:
  - job: PackageJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'compiled-classes'
        downloadPath: 'compiled-classes'
    - script: |
        echo "Main-Class: chadsVascCalculatorGUI" > MANIFEST.MF
        ls -R compiled-classes
        jar cvfm cha2ds2-vasc.jar MANIFEST.MF -C compiled-classes .
      displayName: 'Create JAR File'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'cha2ds2-vasc.jar'
        ArtifactName: 'cha2ds2-vasc'
        publishLocation: 'Container'  

- stage: Archive
  displayName: 'Archive Artifacts'
  jobs:
  - job: ArchiveJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'cha2ds2-vasc'
        downloadPath: 'cha2ds2-vasc'
    - script: |
        echo "Contents of downloaded JAR package:"
        ls -lR $(System.DefaultWorkingDirectory)/cha2ds2-vasc
      displayName: 'Verify Artifact Download'
